name: Review PR

on:
  pull_request:
    branches:
      - main

jobs:
  # Check changed files in PR
  changed_files:
    runs-on: ubuntu-latest
    name: Check changed files in PR
    permissions:
      pull-requests: read

    services:
      postgres-server:
        image: postgres
        env:
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zabbix-server:
        image: zabbix/zabbix-server-pgsql:latest
        env:
          DB_SERVER_HOST: postgres-server
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix

      zabbix-web:
        image: zabbix/zabbix-web-nginx-pgsql:latest
        ports:
          - "8080:8080"
        env:
          DB_SERVER_HOST: postgres-server
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
          PHP_TZ: Europe/Riga

    steps:
      - name: Install python3
        run: |
          ls .github
          sudo apt update
          sudo apt install -y python3 python3-pip python-is-python3
          pip3 install -r .github/workflows/scripts/requirements.txt
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46 # v46
        with:
          json: true
          escape_json: false
          write_output_files: true

      - name: Wait for Zabbix API
        run: |
          .github/workflows/scripts/wait_instance.py

      - name: Run checks
        run: |
          .github/workflows/scripts/check_rules.py
